export type FETCH_RESULT_REQUEST = "FETCH_RESULT_REQUEST";
export type FETCH_RESULT_FAILURE = "FETCH_RESULT_FAILURE";
export type FETCH_RESULT_SUCCESS = "FETCH_RESULT_SUCCESS";

export type API_ERROR = "API_ERROR";

export type DEMO_GET_METADATA_REQUEST = "DEMO_GET_METADATA_REQUEST";
export type DEMO_GET_METADATA_FAILURE = "DEMO_GET_METADATA_FAILURE";
export type DEMO_GET_METADATA_SUCCESS = "DEMO_GET_METADATA_SUCCESS";