export type FETCH_RESULT_REQUEST = "FETCH_RESULT_REQUEST";
export type FETCH_RESULT_FAILURE = "FETCH_RESULT_FAILURE";
export type FETCH_RESULT_SUCCESS = "FETCH_RESULT_SUCCESS";

export type API_ERROR = "API_ERROR";

export type DEMO_GET_METADATA_REQUEST = "DEMO_GET_METADATA_REQUEST";
export type DEMO_GET_METADATA_FAILURE = "DEMO_GET_METADATA_FAILURE";
export type DEMO_GET_METADATA_SUCCESS = "DEMO_GET_METADATA_SUCCESS";

export type DEMO_SET_PREREQUISITES_REQUEST = "DEMO_SET_PREREQUISITES_REQUEST";
export type DEMO_SET_PREREQUISITES_FAILURE = "DEMO_SET_PREREQUISITES_FAILURE";
export type DEMO_SET_PREREQUISITES_SUCCESS = "DEMO_SET_PREREQUISITES_SUCCESS";

export type DEMO_RUN_REQUEST = "DEMO_RUN_REQUEST";
export type DEMO_RUN_FAILURE = "DEMO_RUN_FAILURE";
export type DEMO_RUN_SUCCESS = "DEMO_RUN_SUCCESS";

export type DEMO_PARAMS_INIT = "DEMO_PARAMS_INIT";
export type DEMO_PARAMS_CHANGE = "DEMO_PARAMS_CHANGE";