export type API_ERROR = "API_ERROR";
export type API_ERROR_RELOAD = "API_ERROR_RELOAD";

export type DEMO_GET_CONTEXT_REQUEST = "DEMO_GET_CONTEXT_REQUEST";
export type DEMO_GET_CONTEXT_SUCCESS = "DEMO_GET_CONTEXT_SUCCESS";

export type DEMO_REFRESH_PROGRESS = "DEMO_REFRESH_PROGRESS";

export type DEMO_GET_METADATA_REQUEST = "DEMO_GET_METADATA_REQUEST";
export type DEMO_GET_METADATA_FAILURE = "DEMO_GET_METADATA_FAILURE";
export type DEMO_GET_METADATA_SUCCESS = "DEMO_GET_METADATA_SUCCESS";

export type DEMO_SET_PREREQUISITES_REQUEST = "DEMO_SET_PREREQUISITES_REQUEST";
export type DEMO_SET_PREREQUISITES_FAILURE = "DEMO_SET_PREREQUISITES_FAILURE";
export type DEMO_SET_PREREQUISITES_SUCCESS = "DEMO_SET_PREREQUISITES_SUCCESS";

export type DEMO_RUN_REQUEST = "DEMO_RUN_REQUEST";
export type DEMO_RUN_FAILURE = "DEMO_RUN_FAILURE";
export type DEMO_RUN_SUCCESS = "DEMO_RUN_SUCCESS";

export type DEMO_HIDE_RESULTS = "DEMO_HIDE_RESULTS";

export type DEMO_TOGGLE_SHARE_MESSAGE = "DEMO_TOGGLE_SHARE_MESSAGE";

export type PARAMS_INIT = "PARAMS_INIT";
export type PARAMS_CHANGE = "PARAMS_CHANGE";
export type PARAMS_CHANGE_FILE = "PARAMS_CHANGE_FILE";
export type PARAMS_HIDE_INVALID_UPLOAD_MESSAGE = "PARAMS_HIDE_INVALID_UPLOAD_MESSAGE";

export type SETTINGS_RESET_DB_DIALOG_SHOW = "SETTINGS_RESET_DB_DIALOG_SHOW";
export type SETTINGS_RESET_DB_DIALOG_CLOSE = "SETTINGS_RESET_DB_DIALOG_CLOSE";

export type SETTINGS_RESET_DB_REQUEST = "SETTINGS_RESET_DB_REQUEST";
export type SETTINGS_RESET_DB_SUCCESS = "SETTINGS_RESET_DB_SUCCESS";
export type SETTINGS_RESET_DB_FAILURE = "SETTINGS_RESET_DB_FAILURE";

export type SETTINGS_RESET_PROGRESS_DIALOG_SHOW = "SETTINGS_RESET_PROGRESS_DIALOG_SHOW";
export type SETTINGS_RESET_PROGRESS_DIALOG_CLOSE = "SETTINGS_RESET_PROGRESS_DIALOG_CLOSE";

export type SETTINGS_CLEAR_PROGRESS = "SETTINGS_CLEAR_PROGRESS";

export type NAVIGATION_WENT_TO_MAIN_PAGE = "NAVIGATION_WENT_TO_MAIN_PAGE";
export type NAVIGATION_WENT_TO_DEMO_PAGE = "NAVIGATION_WENT_TO_DEMO_PAGE";
