export type API_ERROR = "API_ERROR";

export type DEMO_GET_METADATA_REQUEST = "DEMO_GET_METADATA_REQUEST";
export type DEMO_GET_METADATA_FAILURE = "DEMO_GET_METADATA_FAILURE";
export type DEMO_GET_METADATA_SUCCESS = "DEMO_GET_METADATA_SUCCESS";

export type DEMO_SET_PREREQUISITES_REQUEST = "DEMO_SET_PREREQUISITES_REQUEST";
export type DEMO_SET_PREREQUISITES_FAILURE = "DEMO_SET_PREREQUISITES_FAILURE";
export type DEMO_SET_PREREQUISITES_SUCCESS = "DEMO_SET_PREREQUISITES_SUCCESS";

export type DEMO_RUN_REQUEST = "DEMO_RUN_REQUEST";
export type DEMO_RUN_FAILURE = "DEMO_RUN_FAILURE";
export type DEMO_RUN_SUCCESS = "DEMO_RUN_SUCCESS";

export type DEMO_HIDE_RESULTS = "DEMO_HIDE_RESULTS";

export type DEMO_TOGGLE_SHARE_MESSAGE = "DEMO_TOGGLE_SHARE_MESSAGE";

export type PARAMS_INIT = "PARAMS_INIT";
export type PARAMS_CHANGE = "PARAMS_CHANGE";
export type PARAMS_CHANGE_FILE = "PARAMS_CHANGE_FILE";
export type PARAMS_HIDE_INVALID_UPLOAD_MESSAGE = "PARAMS_HIDE_INVALID_UPLOAD_MESSAGE";

export type PROGRESS_GET_VERSIONS_REQUEST = "PROGRESS_GET_VERSIONS_REQUEST";
export type PROGRESS_GET_VERSIONS_FAILURE = "PROGRESS_GET_VERSIONS_FAILURE";
export type PROGRESS_GET_VERSIONS_SUCCESS = "PROGRESS_GET_VERSIONS_SUCCESS";

export type PROGRESS_SAVE = "PROGRESS_SAVE";